#!/usr/bin/bash

###############################################################################################################################################################################################################################
# Gestion des services #
########################
#RUN systemctl enable start_container
#COPY ./start.sh /usr/local/bin/start.sh
#RUN chmod +x /usr/local/bin/start.sh
#COPY ./services/start.service     /etc/systemd/system/start_container.service
#COPY ./services/novnc.service     /etc/systemd/system/novnc.service
#COPY ./services/tigervnc.service  /etc/systemd/system/tigervncserver.service
