###################################
name: Build and Push Docker Image #
###################################
#
#######################################################################
on:
 workflow_dispatch:
  inputs:
   dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: 'Dockerfile'
   image-tag:
    description: 'Image tag'
    required: true
    default: 'latest'
